### ISSUE TITLE
v0.10.0: common widget methods now require qualified calls when importing prelude or multiple traits

### ISSUE THREAD

**Issue by awused** [gtk-rs/gtk4-rs#2118]
**Bug description**

I've defined a MainWindow for my application, but after updating to 0.10.0 many common method names are duplicated across many traits when I import the gtk4-rs prelude. This example isn't complete but I think it's enough to illustrate the problem:

```rust
glib::wrapper! {                                                                                                                                                                                                                 
    pub struct MainWindow(ObjectSubclass<imp::MainWindow>)                                                                                                                                                                       
        @extends gtk::Widget, gtk::ApplicationWindow, gtk::Window,                                                                                                                                                               
        @implements gtk::Accessible, gtk::Buildable, gtk::ConstraintTarget, gtk::ShortcutManager, gtk::Native, gtk::Root, ActionGroup, ActionMap;                                                                                
}

use gtk::prelude::*;

let window = MainWindow::new(application);
let display = window.display(); // newly ambiguous with v0.10.0;
let focus = window.focus(); // ditto
```


**Backtrace**

```
error[E0034]: multiple applicable items in scope
  --> src/gui/applications/open_with.rs:82:34
   |
82 |         let display = window.display();
   |                                  ^^^^^^^ multiple `display` found
   |
   = note: candidate #1 is defined in an impl of the trait `gtk4::prelude::AppLaunchContextExt` for the type `O`
   = note: candidate #2 is defined in an impl of the trait `gtk4::prelude::DeviceExt` for the type `O`
   = note: candidate #3 is defined in an impl of the trait `gtk4::prelude::DragExt` for the type `O`
   = note: candidate #4 is defined in an impl of the trait `gtk4::prelude::DrawContextExt` for the type `O`
   = note: and 9 others
```

**Comment by sdroege** [comment]
That would require renaming `display()` to something else in all but one trait so the name is unique again.

**Comment by bilelmoussaoui** [comment]
Not much we can do about it because there would always be more conflicting names.

**Comment by awused** [comment]
I just stopped using the prelude since it was causing more issues than it was solving.
