### ISSUE TITLE
Conflicting implementations for multiple structs after gir-files update

### ISSUE THREAD

**Issue by thewildtree** [gtk-rs/gtk4-rs#2315]
I'm using `gtk4-rs` @ `main` in my project and after a recent `cargo update` the build broke completely for me. `cargo build` just prints hundreds of 'conflicting implementation' errors and that's it.

I suspect this broke recently in 8ec0a0d075b27faf61de4eee5dcfb2bef44ab1fa.

My project was using `features = ["v4_6"]` but changing it to some newer version just produces a slightly different wall of errors.

Examples below:
<details>
<summary>Click here</summary>

```
error[E0119]: conflicting implementations of trait `Borrow<auto::editable::Editable>` for type `auto::text::Text`
  --> /Users/pbrzez-dev/.cargo/git/checkouts/gtk4-rs-ff2bc21858344a74/a27955b/gtk4/src/auto/text.rs:45:1
   |
24 | / glib::wrapper! {
25 | |     #[doc(alias = "GtkText")]
26 | |     pub struct Text(Object<ffi::GtkText>) @extends Widget, @implements Accessible, Buildable, ConstraintTarget, AccessibleText, Editable;
...  |
31 | | }
   | |_- first implementation here
...
45 | / glib::wrapper! {
46 | |     #[doc(alias = "GtkText")]
47 | |     pub struct Text(Object<ffi::GtkText>) @extends Widget, @implements Buildable, ConstraintTarget, Editable;
...  |
52 | | }
   | |_^ conflicting implementation for `auto::text::Text`
   |
   = note: this error originates in the macro `$crate::glib_object_wrapper` which comes from the expansion of the macro `glib::wrapper` (in Nightly builds, run with -Z macro-backtrace for more info)
```
```
error[E0119]: conflicting implementations of trait `glib::translate::FromGlibPtrBorrow<*mut GtkLabel>` for type `auto::label::Label`
  --> /Users/pbrzez-dev/.cargo/git/checkouts/gtk4-rs-ff2bc21858344a74/a27955b/gtk4/src/auto/label.rs:63:1
   |
31 | / glib::wrapper! {
32 | |     #[doc(alias = "GtkLabel")]
33 | |     pub struct Label(Object<ffi::GtkLabel>) @extends Widget, @implements Accessible, Buildable, ConstraintTarget, AccessibleHypertext, AccessibleText;
...  |
38 | | }
   | |_- first implementation here
...
63 | / glib::wrapper! {
64 | |     #[doc(alias = "GtkLabel")]
65 | |     pub struct Label(Object<ffi::GtkLabel>) @extends Widget, @implements Buildable, ConstraintTarget;
...  |
70 | | }
   | |_^ conflicting implementation for `auto::label::Label`
   |
   = note: this error originates in the macro `$crate::glib_object_wrapper` which comes from the expansion of the macro `glib::wrapper` (in Nightly builds, run with -Z macro-backtrace for more info)
```

```
error[E0119]: conflicting implementations of trait `glib::translate::ToGlibPtr<'_, *const GtkText>` for type `auto::text::Text`
  --> /Users/pbrzez-dev/.cargo/git/checkouts/gtk4-rs-ff2bc21858344a74/a27955b/gtk4/src/auto/text.rs:45:1
   |
24 | / glib::wrapper! {
25 | |     #[doc(alias = "GtkText")]
26 | |     pub struct Text(Object<ffi::GtkText>) @extends Widget, @implements Accessible, Buildable, ConstraintTarget, AccessibleText, Editable;
...  |
31 | | }
   | |_- first implementation here
...
45 | / glib::wrapper! {
46 | |     #[doc(alias = "GtkText")]
47 | |     pub struct Text(Object<ffi::GtkText>) @extends Widget, @implements Buildable, ConstraintTarget, Editable;
...  |
52 | | }
   | |_^ conflicting implementation for `auto::text::Text`
   |
   = note: this error originates in the macro `$crate::glib_object_wrapper` which comes from the expansion of the macro `glib::wrapper` (in Nightly builds, run with -Z macro-backtrace for more info)
```
</details>

Let me know if anything more is needed to investigate.
